name: aws-s3-baseline
title: aws-s3-baseline
maintainer: MITRE InSpec Team
copyright: MITRE, 2022
copyright_email: inspec@mitre.org
license: Apache-2.0
summary: "InSpec profile to test if you have public buckets or objects"
version: 1.5.2

inspec_version: ">= 4.0"

supports:
- platform: aws

depends:
- name: inspec-aws
  git: https://github.com/inspec/inspec-aws.git

inputs:
- name: single_bucket
  description: "The name of the single bucket you wish to scan"
  type: string
  value: ""

- name: exception_bucket_list
  description: "List of buckets that should be exempted from review"
  type: array
  value:
  - ""
